repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      -  id: check-yaml
      -  id: end-of-file-fixer
      -  id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
        files: \.tf$
      - id: terraform_docs
        files: \.(tf|md)$
        args:
          - --hook-config=--path-to-file=README.md
      - id: terraform_tflint
        files: \.tf$
        exclude: ^examples/
      - id: terraform_checkov
        files: \.tf$
        exclude: ^examples/
        args:
          - --args=--config-file ./.checkov-config.yml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: local
    hooks:
      - id: terraform-test
        name: Terraform test
        entry: terraform test
        language: system
        files: \.(tf|tftest\.hcl)$
        pass_filenames: false
