name: Validate the source code
on:
  workflow_call:
    inputs:
      terraform_directory:
        required: false
        type: string
        description: "Directory in which the Terraform configuration is available"
        default: "."
    secrets:
      GH_TOKEN:
        required: true
        description: "GitHub token to access the repository"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      issues: read # for publish-unit-test-result-action to read issues
      checks: write # for publish-unit-test-result-action to create checks
      pull-requests: write # for publish-unit-test-result-action to comment on PRs
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform format
        id: tf-fmt
        run: terraform -chdir=${{inputs.terraform_directory}} fmt -check
        continue-on-error: true
      - name: Terraform init
        id: tf-init
        run: terraform -chdir=${{inputs.terraform_directory}} init
      - name: Terraform validate
        id: tf-validate
        run: terraform -chdir=${{inputs.terraform_directory}} validate -no-color
      - name: Terraform test
        id: tf-test
        run: terraform -chdir=${{inputs.terraform_directory}} test -junit-xml=test-results.xml
        continue-on-error: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{inputs.terraform_directory}}/test-results.xml
          check_name: Terraform Test Results
          comment_mode: always
          deduplicate_classes_by_file_name: false

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: terraform-test-results
          path: ${{inputs.terraform_directory}}/test-results.xml
          retention-days: 30
      - name: Checkov validation
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli
          output_file_path: console
          config_file: .checkov-config.yml
